spring:
  application:
    name: graphql-api
  datasource:
    url: jdbc:postgresql://localhost:5432/sentryc_interview
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


graphql:
  servlet:
    mapping: /graphql
    enabled: true
