spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true  # Format SQL queries
        use_sql_comments: true  # Add comments to SQL queries
        hbm2ddl:
          import_files: import.sql  # Ensure this points to your test-data.sql if needed
