#data source
spring:
  application:
    name: graphql-api
  datasource:
    url: jdbc:postgresql://localhost:5432/${postgres.db.name}
    username: ${postgres.db.name}
    password: ${postgres.db.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

